[package]
name = "camd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.71"
clap = "^2.33.0"
log = "^0.4.19"
pretty_env_logger = "^0.5.0"
tokio = { version = "^1.29.1", features = ["full"] }
